excluded:
  - Pods

disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace # this shall remain ignored
- function_body_length
- line_length # (keep this rule ignored -- we prefer line wrapping)
- todo
- multiple_closures_with_trailing_closure


opt_in_rules:
- force_unwrapping
- cyclomatic_complexity


file_length:
  warning: 800
  error: 1000

force_unwrapping:
  severity: error

function_parameter_count:
  warning: 7
  error: 7

identifier_name:
  min_length: 2
  max_length:
    warning: 70
    error: 100
  excluded:
    - id
    - i
    - r
    - b
    - g
    - a
    - x
    - y
    - Pods
